name: Deploy to server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Clear npm cache
        run: npm cache clean --force

      - name: SSH into server and deploy
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.SSH_USER }}
          host: ${{ secrets.SSH_HOST }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd savunmanfrontend # Projeye özgü dizin adını buraya yazın
            git pull
            docker stop savunmanfrontend-container || true
            docker rm savunmanfrontend-container || true
            docker rmi savunmanfrontend -f || true
            docker build -t savunmanfrontend .
            docker run -d -p 8032:8032 --name savunmanfrontend-container savunmanfrontend
